name: onlineshop
version: '3.9'
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  server-app:
    image: sheff2000/server-app:0.2.1
    ports:
      - "3000:3000"
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=UseDevelopmentStorage=true
      - AZURE_ACCOUNT_NAME=devstoreaccount1
      - AZURE_ACCOUNT_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      - AZURE_TABLE_POINT=http://azurite:10002/devstoreaccount1
      - AZURE_BLOB_POINT=http://azurite:10000/devstoreaccount1
      - AZURE_QUEUE_POINT=http://azurite:10001/devstoreaccount1
      - TABLE_NAME_CATEGORY=cat
      - TABLE_NAME_PRODUCT=product
      - CONTAINER_NAME=product
      - BASE_BLOB_URL=http://azurite:10000/devstoreaccount1
      - NAME_QUEUE=resizeimage
  
    depends_on:
      - azurite

  front-app:
    image: sheff2000/front-app:0.1
    ports:
      - "80:80"
    environment:
      - VUE_APP_API_URL=http://server-app:3000
    depends_on:
      - azurite

  image-resize:
    image: sheff2000/image-resize:0.1
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=UseDevelopmentStorage=true
      - AZURE_ACCOUNT_NAME=devstoreaccount1
      - AZURE_ACCOUNT_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      - AZURE_TABLE_POINT=http://azurite:10002/devstoreaccount1
      - AZURE_BLOB_POINT=http://azurite:10000/devstoreaccount1
      - AZURE_QUEUE_POINT=http://azurite:10001/devstoreaccount1
      - CONTAINER_NAME=product
      - TABLE_NAME_PRODUCT=product
      - NAME_QUEUE=resizeimage
    depends_on:
      - azurite